<a href="https://colab.research.google.com/github/kaustubh-Beta/ColabNbs/blob/master/pytorchBasics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch basics 1

In this tutorial we will learn the following :

1.  Tensors in Pytorch
2.  Operations with tensors
3.  Inter-conversion of numpy array and pytorch tensors 


In [0]:
from __future__ import print_function
import torch
import numpy as np

## Creating tensors in pytorch

---

### 1. Creating an uninitialized tensor

In [0]:
# Construction an uninitialized matrix
A = torch.empty(3,3)
print(A)
# NOTE : the above empty method returns a tensor with garbage values of dtype torch.float32

tensor([[2.7556e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])


### 2. Creating a ramndomly initialized tensor

In [0]:
torch.torch.manual_seed(7) # Set initial seed value to generate same random values every time
A1 = torch.rand(3,3)
print(A1)

tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251],
        [0.2071, 0.6297, 0.3653]])


### 3.  Creating a tensor with all the elements zero

In [0]:
A = torch.zeros(3,3, dtype = torch.float32)
print(A)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### 4. Creating the tensors directly from data

In [0]:
A2 = torch.tensor([5,6,7],dtype=torch.float32)
print(A2)

tensor([5., 6., 7.])


## Operations with tensors


---

### 1. Addition operation

In [0]:
torch.torch.manual_seed
a = torch.rand(3,3)
b = torch.rand(3,3)
print("Input array 1 \n%r"%a)
print("Input array 2 \n%r"%b)

# Addition syntax 1
c1 = a+b

# Addition syntax 2
c2 = torch.add(a,b)

# Addition syntax 3
c3 = torch.empty(3,3)
torch.add(a,b, out = c3)

# Addition syntax 4
c4 = torch.torch.clone(b)
c4.add_(a)

print("Method 1 output \n%r"%c1)
print("Method 2 output \n%r"%c2)
print("Method 3 output \n%r"%c3)
print("Method 3 output \n%r"%c4)


Input array 1 
tensor([[0.8513, 0.8549, 0.5509],
        [0.2868, 0.2063, 0.4451],
        [0.3593, 0.7204, 0.0731]])
Input array 2 
tensor([[0.9699, 0.1078, 0.8829],
        [0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797]])
Method 1 output 
tensor([[1.8212, 0.9627, 1.4338],
        [0.7000, 0.9635, 1.1399],
        [0.8802, 1.3136, 0.9528]])
Method 2 output 
tensor([[1.8212, 0.9627, 1.4338],
        [0.7000, 0.9635, 1.1399],
        [0.8802, 1.3136, 0.9528]])
Method 3 output 
tensor([[1.8212, 0.9627, 1.4338],
        [0.7000, 0.9635, 1.1399],
        [0.8802, 1.3136, 0.9528]])
Method 3 output 
tensor([[1.8212, 0.9627, 1.4338],
        [0.7000, 0.9635, 1.1399],
        [0.8802, 1.3136, 0.9528]])


### 2. Multiplication of tensros 

2.A. Dot product

2.B. Cross product or matrix multiplication

2.C. Element wise multiplication

In [0]:
# torch.dot() only takes 1D tensors

a1 = torch.tensor([1,1,1])
a2 = torch.tensor([1,1,1])

c_dot = torch.dot(a1,a2)
c_cross = torch.cross(a1,a2)
print("Input arrays \na1 %r \na2 %r"%(a1,a2))
print("output of dot product : %r"%c_dot)
print("output of cross product : %r"%c_cross)

a = torch.tensor([[1,0],[0,1]])
b = torch.tensor([[3,4],[2,1]])

c_element_wise = torch.mul(a,b) # same can be done with a*b
c_matrix_mul = torch.mm(a,b)

print("\n\nInput arrays \na %r \nb %r"%(a,b))
print("Output for element wise multiplication"%c_element_wise)
print("Output for normal matrix multiplication"%c_matrix_mul)


Input arrays 
a1 tensor([1, 1, 1]) 
a2 tensor([1, 1, 1])
output of dot product : tensor(3)
output of cross product : tensor([0, 0, 0])
output of matmul : tensor(3)


Input arrays 
a tensor([[1, 0],
        [0, 1]]) 
b tensor([[3, 4],
        [2, 1]])
Output for element wise multiplication
Output for normal matrix multiplication


## Converting torch tensor to numpy array

---



In [0]:
a = torch.ones(5)
print("Value of tensor a = %r"%a)

a_numpy = a.numpy()
print("Value of numpy version of a = %r"%a_numpy)

print("\n\nIncrementing all element of just the tensor a by 1 ...\n\n")
a+=1

print("Updated value of tensor a = %r"%a)
print("Updated value of numpy version of a = %r"%a_numpy)

print("\nnow creating a tensor using a numpy array .... \n")

x = np.array([1,2,3,4],dtype=np.float32)
x_tensor = torch.from_numpy(x)

print("Numpy array x = %r"%x)
print("Tensor form of the numpy array x = %r"%x_tensor)

print("\nchanging the value of the tensor form of x...")
x_tensor+=1

print("Updated value of tensor form of x = %r"%x_tensor)
print("Updated value of the numpy array x = %r"%x)

print("\n\nNOTE : change in either the tensor or corresponding numpy array automatically replicates the change in the other")

Value of tensor a = tensor([1., 1., 1., 1., 1.])
Value of numpy version of a = array([1., 1., 1., 1., 1.], dtype=float32)


Incrementing all element of just the tensor a by 1 ...


Updated value of tensor a = tensor([2., 2., 2., 2., 2.])
Updated value of numpy version of a = array([2., 2., 2., 2., 2.], dtype=float32)

now creating a tensor using a numpy array .... 

Numpy array x = array([1., 2., 3., 4.], dtype=float32)
Tensor form of the numpy array x = tensor([1., 2., 3., 4.])

changing the value of the tensor form of x...
Updated value of tensor form of x = tensor([2., 3., 4., 5.])
Updated value of the numpy array x = array([2., 3., 4., 5.], dtype=float32)


NOTE : change in either the tensor or corresponding numpy array automatically replicates the change in the other
