<a href="https://colab.research.google.com/github/kaustubh-Beta/ColabNbs/blob/master/PytorchIntro/pytorchBasics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch basics 2

In this tutorial we will learn explore the `autograd` package of pytorch. The autograd package provides automatic differentiation for all operations on the tensors. 

We will try to understand this package in a better way. 

---


In [0]:
from __future__ import print_function
import torch
import numpy as np

In [25]:
# Creating a tensor 
x1 = torch.ones(2,2, requires_grad=True)
x2 = torch.ones(2,2, requires_grad=False)

# NOTE : By setting therequires_grad argument we enable the tracking of computation for the tensor 

# To understand the working in a better way we perform some operations on the tensor x
y1 = x1 + 2
y2 = x2 + 2

print("printing the results for tensor with requires_grad flag is set to true ......")
print("Printing the output for the computation : ",y1)
print("Printing the grad_fn attribute of the computation \n")
print(y1.grad_fn)

print("\n\nprinting the results for tensor with requires_grad flag is set to false ......")
print("Printing the output for the computation : ",y2)
print("Printing the grad_fn attribute of the computation \n")
print(y2.grad_fn)

# Take a minute and read below text to understand what just happened !! :-O

printing the results for tensor with requires_grad flag is set to true ......
Printing the output for the computation :  tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
Printing the grad_fn attribute of the computation 



printing the results for tensor with requires_grad flag is set to false ......
Printing the output for the computation :  tensor([[3., 3.],
        [3., 3.]])
Printing the grad_fn attribute of the computation 

None


### What just happened ??????
Once we set the flag `requires_grad = true` for a tensor x1 then any new tensor created because of some operation on x1 will have a `.grad_fn` attribute which would refer a function / operation that was performed on  x1.

For tensor with the `required_grad = False` and for tensor created by user, the value of `.grad_fn` = None  

In [26]:
z = y1*y1*3
out = z.mean()

print("Value of z : %r\n"%z)
print("value of out : %r\n"%out)

# Uncomment the bellow block and read what error is given to understand 
# that we canonly set the value to True for requires_grad_(). Which means 
# you can start to log all the function affecting a tensor in middle of the code
# but to undo that effect later in the code you cannot write requires_grad_(False)
"""
z.requires_grad_(False)
print("Updated value of z : %r\n"%z)
"""

# To avoid creating a log for a perticular operation we can simply use below code
with torch.no_grad():
  z2 = y1*y1*3
  out2 = z2.mean()
print(out2.grad_fn)

Value of z : tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

value of out : tensor(27., grad_fn=<MeanBackward0>)

None


In [27]:
# Performing backpropagation 
out.backward()
print(x1.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


When we set the `.requires_grad`attribute as true for a tensor then all the operations on it are tracked and we can finally call `.backward()` we have all the gradients computed automatically and are stored in `.grad` attribute.

In [32]:
a = torch.ones(1, requires_grad = True)
b = a*2
b = b*2
print(b)

b.backward()
print(a.grad)

tensor([4.], grad_fn=<MulBackward0>)
tensor([4.])


In [33]:
# when the function y is not a scalar value 
x = torch.ones(3, requires_grad = True)

y = x*2

y = y*2

print(y)
# Note : the autograd is not able to compute the full jacobian directly
# But we can calculate vector-jacobian product

tensor([4., 4., 4.], grad_fn=<MulBackward0>)


In [34]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([4.0000e-01, 4.0000e+00, 4.0000e-04])
